### PR TITLE
BF: Use the `sklearn.base` interface, instead of deprecated `sklearn.linear_model.base`

### LINKED ISSUE #2010: Issue with sklearn update 0.22 - Attribute Error
In sfm.py we are getting attribute error as there is a change in new sklearn update
"""
Line 358
 elif (isinstance(solver, opt.SKLearnLinearSolver) or
            has_sklearn and isinstance(solver, lm.base.LinearModel)):
Getting no         elif (isinstance(solver, opt.SKLearnLinearSolver) or
>           has_sklearn and isinstance(solver, lm.base.LinearModel)):
E           AttributeError: module 'sklearn.linear_model' has no attribute 'base'

../sfm.py:359: AttributeError
"""
@arokem can you look into it? It is currently blocking all PRs. 
You will see the error if you upgrade sklearn and run test_sfm.py

### PR DESCRIPTION
**Pull request by arokem**
This works with the new release 0.22, but also with older versions (at least one version back).

Fixes #2010

### CODE REVIEW

**Comment by skoudoro** [comment]
Thank you @arokem! LGTM, merging
